// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9QwJZvzRV55qfziyFbg3S5hIEgIVSAI4',
    appId: '1:226874086590:web:9f501089569af8d66ebaef',
    messagingSenderId: '226874086590',
    projectId: 'cinelog-c3836',
    authDomain: 'cinelog-c3836.firebaseapp.com',
    storageBucket: 'cinelog-c3836.firebasestorage.app',
    measurementId: 'G-B8M9CJV1D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNhwCEl9K-SVgP3BfD7C1ggg8mwfX1aY',
    appId: '1:226874086590:android:74dab4b7b6bbbfe16ebaef',
    messagingSenderId: '226874086590',
    projectId: 'cinelog-c3836',
    storageBucket: 'cinelog-c3836.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1F-tTIbKJKmAWzD_MjqGuZbT82z6AstM',
    appId: '1:226874086590:ios:8e283c1174bf2e536ebaef',
    messagingSenderId: '226874086590',
    projectId: 'cinelog-c3836',
    storageBucket: 'cinelog-c3836.firebasestorage.app',
    iosBundleId: 'com.example.cinelog',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1F-tTIbKJKmAWzD_MjqGuZbT82z6AstM',
    appId: '1:226874086590:ios:8e283c1174bf2e536ebaef',
    messagingSenderId: '226874086590',
    projectId: 'cinelog-c3836',
    storageBucket: 'cinelog-c3836.firebasestorage.app',
    iosBundleId: 'com.example.cinelog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9QwJZvzRV55qfziyFbg3S5hIEgIVSAI4',
    appId: '1:226874086590:web:c4aa8c2c3166f2686ebaef',
    messagingSenderId: '226874086590',
    projectId: 'cinelog-c3836',
    authDomain: 'cinelog-c3836.firebaseapp.com',
    storageBucket: 'cinelog-c3836.firebasestorage.app',
    measurementId: 'G-KBW4NWSZPY',
  );
}
